In [151]:
import pandas as pd

In [152]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [153]:
data = pd.read_csv('/content/AirQuality.csv',sep=';')

In [154]:
data

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
data=data.drop(columns=['Date','Time','Unnamed: 15','Unnamed: 16'])

In [156]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578"
1,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255"
2,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502"
3,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867"
4,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [157]:
cols_to_fix=['CO(GT)','C6H6(GT)','T','RH','AH']

In [158]:
for column in cols_to_fix:
  data[column]=data[column].str.replace(',','.')
  data[column]=data[column].astype(float)

In [159]:
data=data.astype({'CO(GT)':'float64','C6H6(GT)':'float64','T':'float64','RH':'float64','AH':'float64'})

In [160]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
data.dropna(inplace=True)

In [162]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [163]:
data.drop_duplicates(inplace=True,ignore_index=True)

In [164]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9321,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9322,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9323,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9324,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9325,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [165]:
def remove_outliers(data,column,lower=0.01,higher=0.99):
  low=data[column].quantile(lower)
  high=data[column].quantile(higher)
  return data[(data[column]>=low)&(data[column]<=high)]

In [166]:
df=data.copy()

In [167]:
for col in df.columns:
  df=remove_outliers(df,col)

In [168]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9321,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9322,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9323,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9324,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9325,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [169]:
df=df.reset_index(drop=True)

In [170]:
data

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9321,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9322,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9323,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9324,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9325,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [171]:
pt=PowerTransformer(method='yeo-johnson')

In [172]:
df=pd.DataFrame(pt.fit_transform(df),columns=df.columns)

In [173]:
df

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,0.717657,1.359569,3.144706,0.469115,0.650631,0.103915,0.852179,0.445186,0.842510,0.904265,-0.486426,0.029489,-0.528643
1,0.327523,1.066370,3.129000,0.061870,0.307194,-0.198976,1.302519,0.114069,0.486934,0.113039,-0.514202,-0.035260,-0.582953
2,0.449867,1.542256,3.117976,0.000834,0.247243,-0.064695,1.172217,0.461262,0.476305,0.384448,-0.640226,0.311461,-0.541562
3,0.449867,1.429023,3.114045,0.031204,0.280949,0.132892,0.989002,0.590807,0.553454,0.729606,-0.718001,0.656632,-0.478720
4,0.105996,0.980758,3.098274,-0.352444,-0.135384,-0.064695,1.421691,0.493493,0.304127,0.480566,-0.700944,0.633185,-0.475044
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8186,1.095609,1.160873,-0.318385,0.751635,0.860143,1.598481,-1.045113,1.749857,-0.000479,2.155206,0.378672,-0.942879,-0.530348
8187,0.579915,0.519354,-0.318385,0.384235,0.578587,1.014008,-0.814888,1.556120,-0.285985,0.906956,0.660166,-1.182723,-0.605355
8188,0.579915,0.431499,-0.318385,0.555639,0.715238,0.720670,-0.818452,1.486217,-0.345247,0.432487,0.979363,-1.394451,-0.718341
8189,0.387731,-0.141017,-0.318385,0.077313,0.329710,0.438196,-0.462590,1.158373,-0.853732,-0.419952,1.157113,-1.564000,-0.901072
8190,0.449867,0.137065,-0.318385,0.469115,0.654427,0.584156,-0.635882,1.364612,-0.631561,-0.299154,1.182832,-1.577238,-0.916007

In [174]:
X=df.drop('AH',axis=1)

In [175]:
y=df['AH']

In [176]:
X

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH
0,0.717657,1.359569,3.144706,0.469115,0.650631,0.103915,0.852179,0.445186,0.842510,0.904265,-0.486426,0.029489
1,0.327523,1.066370,3.129000,0.061870,0.307194,-0.198976,1.302519,0.114069,0.486934,0.113039,-0.514202,-0.035260
2,0.449867,1.542256,3.117976,0.000834,0.247243,-0.064695,1.172217,0.461262,0.476305,0.384448,-0.640226,0.311461
3,0.449867,1.429023,3.114045,0.031204,0.280949,0.132892,0.989002,0.590807,0.553454,0.729606,-0.718001,0.656632
4,0.105996,0.980758,3.098274,-0.352444,-0.135384,-0.064695,1.421691,0.493493,0.304127,0.480566,-0.700944,0.633185
...,...,...,...,...,...,...,...,...,...,...,...,...
8186,1.095609,1.160873,-0.318385,0.751635,0.860143,1.598481,-1.045113,1.749857,-0.000479,2.155206,0.378672,-0.942879
8187,0.579915,0.519354,-0.318385,0.384235,0.578587,1.014008,-0.814888,1.556120,-0.285985,0.906956,0.660166,-1.182723
8188,0.579915,0.431499,-0.318385,0.555639,0.715238,0.720670,-0.818452,1.486217,-0.345247,0.432487,0.979363,-1.394451
8189,0.387731,-0.141017,-0.318385,0.077313,0.329710,0.438196,-0.462590,1.158373,-0.853732,-0.419952,1.157113,-1.564000
8190,0.449867,0.137065,-0.318385,0.469115,0.654427,0.584156,-0.635882,1.364612,-0.631561,-0.299154,1.182832,-1.577238

In [177]:
y

0      -0.528643
1      -0.582953
2      -0.541562
3      -0.478720
4      -0.475044
          ...
8186   -0.530348
8187   -0.605355
8188   -0.718341
8189   -0.901072
8190   -0.916007
Name: AH, Length: 8191, dtype: float64

In [178]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=6,shuffle=True)

In [179]:
X_train

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH
415,-1.612140,-0.566375,3.083746,-0.897439,-1.236053,-0.493446,2.422218,-0.232461,-0.702528,-0.621312,-0.613729,-0.573928
7718,0.105996,0.531933,-0.318385,-0.217174,0.027350,0.501404,-0.718422,1.039424,-0.244668,0.823594,-0.568946,0.822446
5049,1.612341,1.307594,-0.318385,2.920109,2.014074,1.810411,-1.164330,0.254411,1.261917,1.379458,0.198372,0.563213
5571,0.449867,0.194799,-0.318385,0.108419,0.352244,0.467361,0.426160,0.365210,-0.138462,0.123655,-0.363035,0.563213
5095,1.260203,1.333569,-0.318385,2.253275,1.711485,1.465595,-1.167824,0.349297,1.131482,1.520449,0.254066,0.442105
...,...,...,...,...,...,...,...,...,...,...,...,...
4714,-1.612140,-0.205871,-0.318385,-0.132079,0.116571,-1.489703,-0.075301,-1.676650,-0.078677,-0.069736,-0.304467,0.691915
2004,-0.343142,-0.637570,-0.318385,-0.743275,-0.781647,-0.568372,1.099589,-0.651440,0.359639,-0.955995,0.672174,-0.002963
227,0.105996,0.857135,-0.318385,-0.088466,0.161299,-0.389544,0.497411,-0.348325,0.780727,-0.715065,0.299049,-0.470377
2761,-0.084561,-0.209917,-0.318385,-0.479050,-0.304312,-0.417961,0.150212,-0.217795,0.125140,-0.201733,0.904427,-0.769615
7050,0.055449,-3.567887,-0.318385,-2.272665,-3.032514,-1.489703,-2.968512,-1.676650,-3.245839,-2.637384,-2.212791,-2.355778

In [180]:
y_train

415    -0.882267
7718   -0.232268
5049    0.826913
5571   -0.103668
5095    0.804953
          ...
4714    0.051925
2004    1.036945
227    -0.113525
2761    0.191194
7050   -2.649475
Name: AH, Length: 6552, dtype: float64

In [181]:
X_test

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH
1529,-1.612140,-0.350960,-0.318385,-0.651242,-0.584158,-0.488743,0.617767,-0.391068,0.028254,-0.286002,-0.163977,0.078456
4186,-0.279023,-0.462995,-0.318385,-0.585052,-0.471948,-0.308769,0.295331,-0.305189,0.051787,-0.301784,0.424682,0.413524
4973,1.345371,1.104989,-0.318385,1.484842,1.310366,1.273921,-0.995775,0.771537,1.150474,1.257659,0.459430,0.721422
2560,-0.168190,-0.071866,-0.318385,-0.258631,-0.024548,-0.251551,0.068669,-0.023722,0.692292,-0.488066,0.979363,-0.420305
2668,2.197802,0.423150,-0.318385,1.989588,1.586408,0.725550,-0.707675,1.261133,1.362790,1.233323,1.029737,-1.039397
...,...,...,...,...,...,...,...,...,...,...,...,...
5887,0.006839,-0.051480,-0.318385,-0.466796,-0.289673,0.263515,0.072370,0.254411,-0.445379,-0.372727,-0.532571,1.293167
7436,-0.372263,-0.930787,-0.318385,-0.925329,-1.374160,-0.323049,1.641706,-0.173563,-1.692313,-0.785206,-1.424990,-0.110007
4179,2.626197,1.625290,-0.318385,3.354187,2.195900,1.254281,-1.146853,1.451377,1.835331,1.384876,1.017113,-0.131204
5389,2.197802,-0.802466,-0.318385,-0.352444,-0.139070,1.195385,0.250603,0.988764,-1.055895,0.395120,-0.430081,-1.013360
6312,0.579915,0.653885,-0.318385,-0.088466,0.157569,1.126716,-0.592688,1.090277,-0.205867,0.842408,-0.577964,0.979015

In [182]:
y_test

1529   -0.163665
4186    1.131796
4973    1.675573
2560    0.908154
2668   -0.138210
          ...
5887    0.056282
7436   -1.197813
4179    1.581115
5389   -0.990917
6312   -0.166679
Name: AH, Length: 1639, dtype: float64

In [183]:
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)
lr_pred=lr_model.predict(X_test)

In [184]:
dt_model=DecisionTreeRegressor()
dt_model.fit(X_train,y_train)
dt_pred=dt_model.predict(X_test)

In [187]:
def Evaluate_model(name,y_test,y_pred):
  print(name)
  r2=r2_score(y_test,y_pred)
  mae=mean_absolute_error(y_test,y_pred)
  mse=mean_squared_error(y_test,y_pred)
  print("r2 : ",r2)
  print("mae :",mae)
  print("mse :",mse)

In [188]:
Evaluate_model(LinearRegression(),y_test,lr_pred)

LinearRegression()
r2 :  0.8573707710965406
mae : 0.28616242562054894
mse : 0.13690238024102133

In [189]:
Evaluate_model(DecisionTreeRegressor(),y_test,lr_pred)

DecisionTreeRegressor()
r2 :  0.8573707710965406
mae : 0.28616242562054894
mse : 0.13690238024102133