In [66]:
import pandas as pd

In [67]:
df=pd.read_csv('/content/dataset_Facebook.csv',sep=";")

In [68]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [70]:
df1=df[['Page total likes','Type','Category']].loc[0:15]
df1

    Page total likes    Type  Category
0             139441   Photo         2
1             139441  Status         2
2             139441   Photo         3
3             139441   Photo         2
4             139441   Photo         2
5             139441  Status         2
6             139441   Photo         3
7             139441   Photo         3
8             139441  Status         2
9             139441   Photo         3
10            139441  Status         2
11            139441   Photo         2
12            139441   Photo         2
13            139441   Photo         2
14            138414   Photo         2
15            138414  Status         2

In [71]:
df2=df[['Page total likes','Type','Category']].loc[16:30]
df2

    Page total likes    Type  Category
16            138414   Photo         3
17            138414   Photo         1
18            138414  Status         3
19            138414   Photo         3
20            138414   Photo         2
21            138414   Photo         1
22            138414    Link         1
23            138414   Photo         3
24            138414  Status         2
25            138458  Status         2
26            138458  Status         2
27            138458   Photo         3
28            138895   Photo         2
29            138895   Video         1
30            138895   Photo         2

In [72]:
df3=df[['Page total likes','Type','Category']].loc[31:100]
df3

     Page total likes    Type  Category
31             138895   Photo         2
32             138895   Photo         3
33             138895   Photo         3
34             138895   Photo         1
35             138895   Photo         2
..                ...     ...       ...
96             137059   Photo         1
97             137059   Photo         2
98             137020  Status         2
99             137020   Photo         1
100            137020   Photo         1

[70 rows x 3 columns]

In [77]:
df4=df[['Post Month','Post Weekday']].loc[0:15]
df4

    Post Month  Post Weekday
0           12             4
1           12             3
2           12             3
3           12             2
4           12             2
5           12             1
6           12             1
7           12             7
8           12             7
9           12             6
10          12             5
11          12             5
12          12             5
13          12             5
14          12             4
15          12             3

In [78]:
df5=df[['like']].loc[0:15]
df5

      like
0     79.0
1    130.0
2     66.0
3   1572.0
4    325.0
5    152.0
6    249.0
7    325.0
8    161.0
9    113.0
10   233.0
11    88.0
12    90.0
13   137.0
14   577.0
15    86.0

In [81]:
merging1=pd.concat([df1,df2,df3])
merging1

     Page total likes    Type  Category
0              139441   Photo         2
1              139441  Status         2
2              139441   Photo         3
3              139441   Photo         2
4              139441   Photo         2
..                ...     ...       ...
96             137059   Photo         1
97             137059   Photo         2
98             137020  Status         2
99             137020   Photo         1
100            137020   Photo         1

[101 rows x 3 columns]

In [80]:
merging2=pd.concat([df4,df5],axis=1)
merging2

    Post Month  Post Weekday    like
0           12             4    79.0
1           12             3   130.0
2           12             3    66.0
3           12             2  1572.0
4           12             2   325.0
5           12             1   152.0
6           12             1   249.0
7           12             7   325.0
8           12             7   161.0
9           12             6   113.0
10          12             5   233.0
11          12             5    88.0
12          12             5    90.0
13          12             5   137.0
14          12             4   577.0
15          12             3    86.0

In [84]:
sort_values=df.sort_values('Page total likes',ascending=False)
sort_values

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [85]:
transposing=df.transpose()
transposing

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [86]:
df.shape

(500, 19)

In [91]:
pivot_table=pd.pivot_table(df,index=['Type','Category'],values='comment')

In [92]:
pivot_table

                   comment
Type   Category
Link   1          2.900000
       2          2.000000
       3          2.000000
Photo  1          5.897297
       2         11.692308
       3          6.913333
Status 1          4.333333
       2          9.921053
       3          2.750000
Video  1         12.285714